export const FAKECONNECTOR_GET_PETS_LIST = "FAKECONNECTOR_GET_PETS_LIST"
export const FAKECONNECTOR_GET_PETS_LIST_SUCCEEDED =
  "FAKECONNECTOR_GET_PETS_LIST_SUCCEEDED"
export const FAKECONNECTOR_GET_PETS_LIST_FAILED =
  "FAKECONNECTOR_GET_PETS_LIST_FAILED"
